# Generated by Django 2.2.12 on 2024-12-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_matiere_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='matieres', to='school.Classe'),
        ),
    ]
