# Generated by Django 2.2.12 on 2024-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20241227_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='classes',
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='school.Matiere'),
        ),
    ]
