repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Use the latest version of Flake8
    hooks:
      - id: flake8
        args: [--max-line-length=88,--exclude=env,migrations]  # Optional: match Black's default line length
        